// This file is generated by generator.py
// Please do not modify this file manually

export type ErrorCode = number;

export const OK: ErrorCode = 0;
export const ERROR_INVALID_REQUEST: ErrorCode = 40001;
export const ERROR_TOKEN_EXPIRED: ErrorCode = 40101;
export const ERROR_TOKEN_INVALID: ErrorCode = 40102;
export const ERROR_MUST_REGISTER: ErrorCode = 40103;
export const ERROR_REGISTER_TIMEOUT: ErrorCode = 40104;
export const ERROR_REGISTER_NOT_FOUND: ErrorCode = 40105;
export const ERROR_INVALID_CREDENTIALS: ErrorCode = 40106;
export const ERROR_USER_NOT_ALLOWED: ErrorCode = 40301;
export const ERROR_USER_EMAIL_NOT_VERIFIED: ErrorCode = 40302;
export const ERROR_NOT_SPECIFIED: ErrorCode = 99999;
