/**
 * Copyright 2025 RAIDS Lab
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by generator.py
// Please do not modify this file manually

export type ErrorCode = number

export const OK: ErrorCode = 0
export const ERROR_INVALID_REQUEST: ErrorCode = 40001
export const ERROR_TOKEN_EXPIRED: ErrorCode = 40101
export const ERROR_TOKEN_INVALID: ErrorCode = 40102
export const ERROR_MUST_REGISTER: ErrorCode = 40103
export const ERROR_REGISTER_TIMEOUT: ErrorCode = 40104
export const ERROR_REGISTER_NOT_FOUND: ErrorCode = 40105
export const ERROR_INVALID_CREDENTIALS: ErrorCode = 40106
export const ERROR_USER_NOT_ALLOWED: ErrorCode = 40301
export const ERROR_USER_EMAIL_NOT_VERIFIED: ErrorCode = 40302
export const ERROR_SERVICE_SSHD_NOT_FOUND: ErrorCode = 40401
export const ERROR_BACKEND: ErrorCode = 50001
export const ERROR_NOT_SPECIFIED: ErrorCode = 99999
