/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalTemplatesRouteRouteImport } from './routes/portal/templates/route'
import { Route as PortalOverviewRouteRouteImport } from './routes/portal/overview/route'
import { Route as PortalMonitorRouteRouteImport } from './routes/portal/monitor/route'
import { Route as PortalTemplatesIndexRouteImport } from './routes/portal/templates/index'
import { Route as PortalOverviewIndexRouteImport } from './routes/portal/overview/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminDataIndexRouteImport } from './routes/admin/data/index'
import { Route as AdminCronjobsIndexRouteImport } from './routes/admin/cronjobs/index'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as PortalUsersNameRouteImport } from './routes/portal/users/$name'
import { Route as PortalSettingsUserRouteImport } from './routes/portal/settings/user'
import { Route as PortalOverviewNodeRouteImport } from './routes/portal/overview/$node'
import { Route as PortalMonitorNetworkRouteImport } from './routes/portal/monitor/network'
import { Route as PortalMonitorIdleRouteImport } from './routes/portal/monitor/idle'
import { Route as PortalMonitorGpuRouteImport } from './routes/portal/monitor/gpu'
import { Route as PortalFilesSplatRouteImport } from './routes/portal/files/$'
import { Route as IngressJupyterNameRouteImport } from './routes/ingress/jupyter.$name'
import { Route as AdminUsersNameRouteImport } from './routes/admin/users/$name'
import { Route as AdminMonitorNetworkRouteImport } from './routes/admin/monitor/network'
import { Route as AdminMonitorIdleRouteImport } from './routes/admin/monitor/idle'
import { Route as AdminMonitorGpuRouteImport } from './routes/admin/monitor/gpu'
import { Route as AdminJobsNameRouteImport } from './routes/admin/jobs/$name'
import { Route as AdminFilesSplatRouteImport } from './routes/admin/files/$'
import { Route as AdminDataIdRouteImport } from './routes/admin/data/$id'
import { Route as AdminAccountsIdRouteImport } from './routes/admin/accounts/$id'
import { Route as PortalJobsNewRouteRouteImport } from './routes/portal/jobs/new/route'
import { Route as PortalJobsDetailRouteRouteImport } from './routes/portal/jobs/detail/route'
import { Route as PortalJobsNewIndexRouteImport } from './routes/portal/jobs/new/index'
import { Route as PortalJobsInterIndexRouteImport } from './routes/portal/jobs/inter/index'
import { Route as PortalJobsDetailIndexRouteImport } from './routes/portal/jobs/detail/index'
import { Route as PortalJobsCustomIndexRouteImport } from './routes/portal/jobs/custom/index'
import { Route as PortalEnvRegistryIndexRouteImport } from './routes/portal/env/registry/index'
import { Route as PortalEnvImagesIndexRouteImport } from './routes/portal/env/images/index'
import { Route as PortalDataModelsIndexRouteImport } from './routes/portal/data/models/index'
import { Route as PortalDataDatasetsIndexRouteImport } from './routes/portal/data/datasets/index'
import { Route as PortalDataBlocksIndexRouteImport } from './routes/portal/data/blocks/index'
import { Route as AdminEnvRegistryIndexRouteImport } from './routes/admin/env/registry/index'
import { Route as AdminEnvImagesIndexRouteImport } from './routes/admin/env/images/index'
import { Route as AdminClusterResourcesIndexRouteImport } from './routes/admin/cluster/resources/index'
import { Route as AdminClusterNodesIndexRouteImport } from './routes/admin/cluster/nodes/index'
import { Route as PortalJobsNewTensorflowPsJobRouteImport } from './routes/portal/jobs/new/tensorflow-ps-job'
import { Route as PortalJobsNewSingleJobRouteImport } from './routes/portal/jobs/new/single-job'
import { Route as PortalJobsNewSeacsJobRouteImport } from './routes/portal/jobs/new/seacs-job'
import { Route as PortalJobsNewPytorchDdpJobRouteImport } from './routes/portal/jobs/new/pytorch-ddp-job'
import { Route as PortalJobsNewJupyterJobRouteImport } from './routes/portal/jobs/new/jupyter-job'
import { Route as PortalJobsNewEmiasJupyterJobRouteImport } from './routes/portal/jobs/new/emias-jupyter-job'
import { Route as PortalJobsNewEmiasJobRouteImport } from './routes/portal/jobs/new/emias-job'
import { Route as PortalJobsDetailNameRouteImport } from './routes/portal/jobs/detail/$name'
import { Route as PortalEnvRegistryNameRouteImport } from './routes/portal/env/registry/$name'
import { Route as PortalDataModelsIdRouteImport } from './routes/portal/data/models/$id'
import { Route as PortalDataDatasetsIdRouteImport } from './routes/portal/data/datasets/$id'
import { Route as PortalDataBlocksIdRouteImport } from './routes/portal/data/blocks/$id'
import { Route as AdminEnvRegistryNameRouteImport } from './routes/admin/env/registry/$name'
import { Route as AdminClusterNodesNodeRouteImport } from './routes/admin/cluster/nodes/$node'

const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalTemplatesRouteRoute = PortalTemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOverviewRouteRoute = PortalOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMonitorRouteRoute = PortalMonitorRouteRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTemplatesIndexRoute = PortalTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTemplatesRouteRoute,
} as any)
const PortalOverviewIndexRoute = PortalOverviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalOverviewRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataIndexRoute = AdminDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCronjobsIndexRoute = AdminCronjobsIndexRouteImport.update({
  id: '/cronjobs/',
  path: '/cronjobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalUsersNameRoute = PortalUsersNameRouteImport.update({
  id: '/users/$name',
  path: '/users/$name',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalSettingsUserRoute = PortalSettingsUserRouteImport.update({
  id: '/settings/user',
  path: '/settings/user',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOverviewNodeRoute = PortalOverviewNodeRouteImport.update({
  id: '/$node',
  path: '/$node',
  getParentRoute: () => PortalOverviewRouteRoute,
} as any)
const PortalMonitorNetworkRoute = PortalMonitorNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => PortalMonitorRouteRoute,
} as any)
const PortalMonitorIdleRoute = PortalMonitorIdleRouteImport.update({
  id: '/idle',
  path: '/idle',
  getParentRoute: () => PortalMonitorRouteRoute,
} as any)
const PortalMonitorGpuRoute = PortalMonitorGpuRouteImport.update({
  id: '/gpu',
  path: '/gpu',
  getParentRoute: () => PortalMonitorRouteRoute,
} as any)
const PortalFilesSplatRoute = PortalFilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => PortalRouteRoute,
} as any)
const IngressJupyterNameRoute = IngressJupyterNameRouteImport.update({
  id: '/ingress/jupyter/$name',
  path: '/ingress/jupyter/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNameRoute = AdminUsersNameRouteImport.update({
  id: '/users/$name',
  path: '/users/$name',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorNetworkRoute = AdminMonitorNetworkRouteImport.update({
  id: '/monitor/network',
  path: '/monitor/network',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorIdleRoute = AdminMonitorIdleRouteImport.update({
  id: '/monitor/idle',
  path: '/monitor/idle',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorGpuRoute = AdminMonitorGpuRouteImport.update({
  id: '/monitor/gpu',
  path: '/monitor/gpu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsNameRoute = AdminJobsNameRouteImport.update({
  id: '/jobs/$name',
  path: '/jobs/$name',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFilesSplatRoute = AdminFilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataIdRoute = AdminDataIdRouteImport.update({
  id: '/data/$id',
  path: '/data/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsIdRoute = AdminAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalJobsNewRouteRoute = PortalJobsNewRouteRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalJobsDetailRouteRoute = PortalJobsDetailRouteRouteImport.update({
  id: '/jobs/detail',
  path: '/jobs/detail',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalJobsNewIndexRoute = PortalJobsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalJobsNewRouteRoute,
} as any)
const PortalJobsInterIndexRoute = PortalJobsInterIndexRouteImport.update({
  id: '/jobs/inter/',
  path: '/jobs/inter/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalJobsDetailIndexRoute = PortalJobsDetailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalJobsDetailRouteRoute,
} as any)
const PortalJobsCustomIndexRoute = PortalJobsCustomIndexRouteImport.update({
  id: '/jobs/custom/',
  path: '/jobs/custom/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalEnvRegistryIndexRoute = PortalEnvRegistryIndexRouteImport.update({
  id: '/env/registry/',
  path: '/env/registry/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalEnvImagesIndexRoute = PortalEnvImagesIndexRouteImport.update({
  id: '/env/images/',
  path: '/env/images/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDataModelsIndexRoute = PortalDataModelsIndexRouteImport.update({
  id: '/data/models/',
  path: '/data/models/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDataDatasetsIndexRoute = PortalDataDatasetsIndexRouteImport.update({
  id: '/data/datasets/',
  path: '/data/datasets/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDataBlocksIndexRoute = PortalDataBlocksIndexRouteImport.update({
  id: '/data/blocks/',
  path: '/data/blocks/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminEnvRegistryIndexRoute = AdminEnvRegistryIndexRouteImport.update({
  id: '/env/registry/',
  path: '/env/registry/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnvImagesIndexRoute = AdminEnvImagesIndexRouteImport.update({
  id: '/env/images/',
  path: '/env/images/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClusterResourcesIndexRoute =
  AdminClusterResourcesIndexRouteImport.update({
    id: '/cluster/resources/',
    path: '/cluster/resources/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminClusterNodesIndexRoute = AdminClusterNodesIndexRouteImport.update({
  id: '/cluster/nodes/',
  path: '/cluster/nodes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalJobsNewTensorflowPsJobRoute =
  PortalJobsNewTensorflowPsJobRouteImport.update({
    id: '/tensorflow-ps-job',
    path: '/tensorflow-ps-job',
    getParentRoute: () => PortalJobsNewRouteRoute,
  } as any)
const PortalJobsNewSingleJobRoute = PortalJobsNewSingleJobRouteImport.update({
  id: '/single-job',
  path: '/single-job',
  getParentRoute: () => PortalJobsNewRouteRoute,
} as any)
const PortalJobsNewSeacsJobRoute = PortalJobsNewSeacsJobRouteImport.update({
  id: '/seacs-job',
  path: '/seacs-job',
  getParentRoute: () => PortalJobsNewRouteRoute,
} as any)
const PortalJobsNewPytorchDdpJobRoute =
  PortalJobsNewPytorchDdpJobRouteImport.update({
    id: '/pytorch-ddp-job',
    path: '/pytorch-ddp-job',
    getParentRoute: () => PortalJobsNewRouteRoute,
  } as any)
const PortalJobsNewJupyterJobRoute = PortalJobsNewJupyterJobRouteImport.update({
  id: '/jupyter-job',
  path: '/jupyter-job',
  getParentRoute: () => PortalJobsNewRouteRoute,
} as any)
const PortalJobsNewEmiasJupyterJobRoute =
  PortalJobsNewEmiasJupyterJobRouteImport.update({
    id: '/emias-jupyter-job',
    path: '/emias-jupyter-job',
    getParentRoute: () => PortalJobsNewRouteRoute,
  } as any)
const PortalJobsNewEmiasJobRoute = PortalJobsNewEmiasJobRouteImport.update({
  id: '/emias-job',
  path: '/emias-job',
  getParentRoute: () => PortalJobsNewRouteRoute,
} as any)
const PortalJobsDetailNameRoute = PortalJobsDetailNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => PortalJobsDetailRouteRoute,
} as any)
const PortalEnvRegistryNameRoute = PortalEnvRegistryNameRouteImport.update({
  id: '/env/registry/$name',
  path: '/env/registry/$name',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDataModelsIdRoute = PortalDataModelsIdRouteImport.update({
  id: '/data/models/$id',
  path: '/data/models/$id',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDataDatasetsIdRoute = PortalDataDatasetsIdRouteImport.update({
  id: '/data/datasets/$id',
  path: '/data/datasets/$id',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDataBlocksIdRoute = PortalDataBlocksIdRouteImport.update({
  id: '/data/blocks/$id',
  path: '/data/blocks/$id',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminEnvRegistryNameRoute = AdminEnvRegistryNameRouteImport.update({
  id: '/env/registry/$name',
  path: '/env/registry/$name',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClusterNodesNodeRoute = AdminClusterNodesNodeRouteImport.update({
  id: '/cluster/nodes/$node',
  path: '/cluster/nodes/$node',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/portal/monitor': typeof PortalMonitorRouteRouteWithChildren
  '/portal/overview': typeof PortalOverviewRouteRouteWithChildren
  '/portal/templates': typeof PortalTemplatesRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/jobs/detail': typeof PortalJobsDetailRouteRouteWithChildren
  '/portal/jobs/new': typeof PortalJobsNewRouteRouteWithChildren
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/data/$id': typeof AdminDataIdRoute
  '/admin/files/$': typeof AdminFilesSplatRoute
  '/admin/jobs/$name': typeof AdminJobsNameRoute
  '/admin/monitor/gpu': typeof AdminMonitorGpuRoute
  '/admin/monitor/idle': typeof AdminMonitorIdleRoute
  '/admin/monitor/network': typeof AdminMonitorNetworkRoute
  '/admin/users/$name': typeof AdminUsersNameRoute
  '/ingress/jupyter/$name': typeof IngressJupyterNameRoute
  '/portal/files/$': typeof PortalFilesSplatRoute
  '/portal/monitor/gpu': typeof PortalMonitorGpuRoute
  '/portal/monitor/idle': typeof PortalMonitorIdleRoute
  '/portal/monitor/network': typeof PortalMonitorNetworkRoute
  '/portal/overview/$node': typeof PortalOverviewNodeRoute
  '/portal/settings/user': typeof PortalSettingsUserRoute
  '/portal/users/$name': typeof PortalUsersNameRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/cronjobs': typeof AdminCronjobsIndexRoute
  '/admin/data': typeof AdminDataIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/portal/overview/': typeof PortalOverviewIndexRoute
  '/portal/templates/': typeof PortalTemplatesIndexRoute
  '/admin/cluster/nodes/$node': typeof AdminClusterNodesNodeRoute
  '/admin/env/registry/$name': typeof AdminEnvRegistryNameRoute
  '/portal/data/blocks/$id': typeof PortalDataBlocksIdRoute
  '/portal/data/datasets/$id': typeof PortalDataDatasetsIdRoute
  '/portal/data/models/$id': typeof PortalDataModelsIdRoute
  '/portal/env/registry/$name': typeof PortalEnvRegistryNameRoute
  '/portal/jobs/detail/$name': typeof PortalJobsDetailNameRoute
  '/portal/jobs/new/emias-job': typeof PortalJobsNewEmiasJobRoute
  '/portal/jobs/new/emias-jupyter-job': typeof PortalJobsNewEmiasJupyterJobRoute
  '/portal/jobs/new/jupyter-job': typeof PortalJobsNewJupyterJobRoute
  '/portal/jobs/new/pytorch-ddp-job': typeof PortalJobsNewPytorchDdpJobRoute
  '/portal/jobs/new/seacs-job': typeof PortalJobsNewSeacsJobRoute
  '/portal/jobs/new/single-job': typeof PortalJobsNewSingleJobRoute
  '/portal/jobs/new/tensorflow-ps-job': typeof PortalJobsNewTensorflowPsJobRoute
  '/admin/cluster/nodes': typeof AdminClusterNodesIndexRoute
  '/admin/cluster/resources': typeof AdminClusterResourcesIndexRoute
  '/admin/env/images': typeof AdminEnvImagesIndexRoute
  '/admin/env/registry': typeof AdminEnvRegistryIndexRoute
  '/portal/data/blocks': typeof PortalDataBlocksIndexRoute
  '/portal/data/datasets': typeof PortalDataDatasetsIndexRoute
  '/portal/data/models': typeof PortalDataModelsIndexRoute
  '/portal/env/images': typeof PortalEnvImagesIndexRoute
  '/portal/env/registry': typeof PortalEnvRegistryIndexRoute
  '/portal/jobs/custom': typeof PortalJobsCustomIndexRoute
  '/portal/jobs/detail/': typeof PortalJobsDetailIndexRoute
  '/portal/jobs/inter': typeof PortalJobsInterIndexRoute
  '/portal/jobs/new/': typeof PortalJobsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal/monitor': typeof PortalMonitorRouteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/data/$id': typeof AdminDataIdRoute
  '/admin/files/$': typeof AdminFilesSplatRoute
  '/admin/jobs/$name': typeof AdminJobsNameRoute
  '/admin/monitor/gpu': typeof AdminMonitorGpuRoute
  '/admin/monitor/idle': typeof AdminMonitorIdleRoute
  '/admin/monitor/network': typeof AdminMonitorNetworkRoute
  '/admin/users/$name': typeof AdminUsersNameRoute
  '/ingress/jupyter/$name': typeof IngressJupyterNameRoute
  '/portal/files/$': typeof PortalFilesSplatRoute
  '/portal/monitor/gpu': typeof PortalMonitorGpuRoute
  '/portal/monitor/idle': typeof PortalMonitorIdleRoute
  '/portal/monitor/network': typeof PortalMonitorNetworkRoute
  '/portal/overview/$node': typeof PortalOverviewNodeRoute
  '/portal/settings/user': typeof PortalSettingsUserRoute
  '/portal/users/$name': typeof PortalUsersNameRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/cronjobs': typeof AdminCronjobsIndexRoute
  '/admin/data': typeof AdminDataIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/portal/overview': typeof PortalOverviewIndexRoute
  '/portal/templates': typeof PortalTemplatesIndexRoute
  '/admin/cluster/nodes/$node': typeof AdminClusterNodesNodeRoute
  '/admin/env/registry/$name': typeof AdminEnvRegistryNameRoute
  '/portal/data/blocks/$id': typeof PortalDataBlocksIdRoute
  '/portal/data/datasets/$id': typeof PortalDataDatasetsIdRoute
  '/portal/data/models/$id': typeof PortalDataModelsIdRoute
  '/portal/env/registry/$name': typeof PortalEnvRegistryNameRoute
  '/portal/jobs/detail/$name': typeof PortalJobsDetailNameRoute
  '/portal/jobs/new/emias-job': typeof PortalJobsNewEmiasJobRoute
  '/portal/jobs/new/emias-jupyter-job': typeof PortalJobsNewEmiasJupyterJobRoute
  '/portal/jobs/new/jupyter-job': typeof PortalJobsNewJupyterJobRoute
  '/portal/jobs/new/pytorch-ddp-job': typeof PortalJobsNewPytorchDdpJobRoute
  '/portal/jobs/new/seacs-job': typeof PortalJobsNewSeacsJobRoute
  '/portal/jobs/new/single-job': typeof PortalJobsNewSingleJobRoute
  '/portal/jobs/new/tensorflow-ps-job': typeof PortalJobsNewTensorflowPsJobRoute
  '/admin/cluster/nodes': typeof AdminClusterNodesIndexRoute
  '/admin/cluster/resources': typeof AdminClusterResourcesIndexRoute
  '/admin/env/images': typeof AdminEnvImagesIndexRoute
  '/admin/env/registry': typeof AdminEnvRegistryIndexRoute
  '/portal/data/blocks': typeof PortalDataBlocksIndexRoute
  '/portal/data/datasets': typeof PortalDataDatasetsIndexRoute
  '/portal/data/models': typeof PortalDataModelsIndexRoute
  '/portal/env/images': typeof PortalEnvImagesIndexRoute
  '/portal/env/registry': typeof PortalEnvRegistryIndexRoute
  '/portal/jobs/custom': typeof PortalJobsCustomIndexRoute
  '/portal/jobs/detail': typeof PortalJobsDetailIndexRoute
  '/portal/jobs/inter': typeof PortalJobsInterIndexRoute
  '/portal/jobs/new': typeof PortalJobsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/portal/monitor': typeof PortalMonitorRouteRouteWithChildren
  '/portal/overview': typeof PortalOverviewRouteRouteWithChildren
  '/portal/templates': typeof PortalTemplatesRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/jobs/detail': typeof PortalJobsDetailRouteRouteWithChildren
  '/portal/jobs/new': typeof PortalJobsNewRouteRouteWithChildren
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/data/$id': typeof AdminDataIdRoute
  '/admin/files/$': typeof AdminFilesSplatRoute
  '/admin/jobs/$name': typeof AdminJobsNameRoute
  '/admin/monitor/gpu': typeof AdminMonitorGpuRoute
  '/admin/monitor/idle': typeof AdminMonitorIdleRoute
  '/admin/monitor/network': typeof AdminMonitorNetworkRoute
  '/admin/users/$name': typeof AdminUsersNameRoute
  '/ingress/jupyter/$name': typeof IngressJupyterNameRoute
  '/portal/files/$': typeof PortalFilesSplatRoute
  '/portal/monitor/gpu': typeof PortalMonitorGpuRoute
  '/portal/monitor/idle': typeof PortalMonitorIdleRoute
  '/portal/monitor/network': typeof PortalMonitorNetworkRoute
  '/portal/overview/$node': typeof PortalOverviewNodeRoute
  '/portal/settings/user': typeof PortalSettingsUserRoute
  '/portal/users/$name': typeof PortalUsersNameRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/cronjobs/': typeof AdminCronjobsIndexRoute
  '/admin/data/': typeof AdminDataIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/portal/overview/': typeof PortalOverviewIndexRoute
  '/portal/templates/': typeof PortalTemplatesIndexRoute
  '/admin/cluster/nodes/$node': typeof AdminClusterNodesNodeRoute
  '/admin/env/registry/$name': typeof AdminEnvRegistryNameRoute
  '/portal/data/blocks/$id': typeof PortalDataBlocksIdRoute
  '/portal/data/datasets/$id': typeof PortalDataDatasetsIdRoute
  '/portal/data/models/$id': typeof PortalDataModelsIdRoute
  '/portal/env/registry/$name': typeof PortalEnvRegistryNameRoute
  '/portal/jobs/detail/$name': typeof PortalJobsDetailNameRoute
  '/portal/jobs/new/emias-job': typeof PortalJobsNewEmiasJobRoute
  '/portal/jobs/new/emias-jupyter-job': typeof PortalJobsNewEmiasJupyterJobRoute
  '/portal/jobs/new/jupyter-job': typeof PortalJobsNewJupyterJobRoute
  '/portal/jobs/new/pytorch-ddp-job': typeof PortalJobsNewPytorchDdpJobRoute
  '/portal/jobs/new/seacs-job': typeof PortalJobsNewSeacsJobRoute
  '/portal/jobs/new/single-job': typeof PortalJobsNewSingleJobRoute
  '/portal/jobs/new/tensorflow-ps-job': typeof PortalJobsNewTensorflowPsJobRoute
  '/admin/cluster/nodes/': typeof AdminClusterNodesIndexRoute
  '/admin/cluster/resources/': typeof AdminClusterResourcesIndexRoute
  '/admin/env/images/': typeof AdminEnvImagesIndexRoute
  '/admin/env/registry/': typeof AdminEnvRegistryIndexRoute
  '/portal/data/blocks/': typeof PortalDataBlocksIndexRoute
  '/portal/data/datasets/': typeof PortalDataDatasetsIndexRoute
  '/portal/data/models/': typeof PortalDataModelsIndexRoute
  '/portal/env/images/': typeof PortalEnvImagesIndexRoute
  '/portal/env/registry/': typeof PortalEnvRegistryIndexRoute
  '/portal/jobs/custom/': typeof PortalJobsCustomIndexRoute
  '/portal/jobs/detail/': typeof PortalJobsDetailIndexRoute
  '/portal/jobs/inter/': typeof PortalJobsInterIndexRoute
  '/portal/jobs/new/': typeof PortalJobsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/portal'
    | '/portal/monitor'
    | '/portal/overview'
    | '/portal/templates'
    | '/admin/'
    | '/auth'
    | '/portal/'
    | '/portal/jobs/detail'
    | '/portal/jobs/new'
    | '/admin/accounts/$id'
    | '/admin/data/$id'
    | '/admin/files/$'
    | '/admin/jobs/$name'
    | '/admin/monitor/gpu'
    | '/admin/monitor/idle'
    | '/admin/monitor/network'
    | '/admin/users/$name'
    | '/ingress/jupyter/$name'
    | '/portal/files/$'
    | '/portal/monitor/gpu'
    | '/portal/monitor/idle'
    | '/portal/monitor/network'
    | '/portal/overview/$node'
    | '/portal/settings/user'
    | '/portal/users/$name'
    | '/admin/accounts'
    | '/admin/cronjobs'
    | '/admin/data'
    | '/admin/jobs'
    | '/admin/settings'
    | '/admin/users'
    | '/portal/overview/'
    | '/portal/templates/'
    | '/admin/cluster/nodes/$node'
    | '/admin/env/registry/$name'
    | '/portal/data/blocks/$id'
    | '/portal/data/datasets/$id'
    | '/portal/data/models/$id'
    | '/portal/env/registry/$name'
    | '/portal/jobs/detail/$name'
    | '/portal/jobs/new/emias-job'
    | '/portal/jobs/new/emias-jupyter-job'
    | '/portal/jobs/new/jupyter-job'
    | '/portal/jobs/new/pytorch-ddp-job'
    | '/portal/jobs/new/seacs-job'
    | '/portal/jobs/new/single-job'
    | '/portal/jobs/new/tensorflow-ps-job'
    | '/admin/cluster/nodes'
    | '/admin/cluster/resources'
    | '/admin/env/images'
    | '/admin/env/registry'
    | '/portal/data/blocks'
    | '/portal/data/datasets'
    | '/portal/data/models'
    | '/portal/env/images'
    | '/portal/env/registry'
    | '/portal/jobs/custom'
    | '/portal/jobs/detail/'
    | '/portal/jobs/inter'
    | '/portal/jobs/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal/monitor'
    | '/admin'
    | '/auth'
    | '/portal'
    | '/admin/accounts/$id'
    | '/admin/data/$id'
    | '/admin/files/$'
    | '/admin/jobs/$name'
    | '/admin/monitor/gpu'
    | '/admin/monitor/idle'
    | '/admin/monitor/network'
    | '/admin/users/$name'
    | '/ingress/jupyter/$name'
    | '/portal/files/$'
    | '/portal/monitor/gpu'
    | '/portal/monitor/idle'
    | '/portal/monitor/network'
    | '/portal/overview/$node'
    | '/portal/settings/user'
    | '/portal/users/$name'
    | '/admin/accounts'
    | '/admin/cronjobs'
    | '/admin/data'
    | '/admin/jobs'
    | '/admin/settings'
    | '/admin/users'
    | '/portal/overview'
    | '/portal/templates'
    | '/admin/cluster/nodes/$node'
    | '/admin/env/registry/$name'
    | '/portal/data/blocks/$id'
    | '/portal/data/datasets/$id'
    | '/portal/data/models/$id'
    | '/portal/env/registry/$name'
    | '/portal/jobs/detail/$name'
    | '/portal/jobs/new/emias-job'
    | '/portal/jobs/new/emias-jupyter-job'
    | '/portal/jobs/new/jupyter-job'
    | '/portal/jobs/new/pytorch-ddp-job'
    | '/portal/jobs/new/seacs-job'
    | '/portal/jobs/new/single-job'
    | '/portal/jobs/new/tensorflow-ps-job'
    | '/admin/cluster/nodes'
    | '/admin/cluster/resources'
    | '/admin/env/images'
    | '/admin/env/registry'
    | '/portal/data/blocks'
    | '/portal/data/datasets'
    | '/portal/data/models'
    | '/portal/env/images'
    | '/portal/env/registry'
    | '/portal/jobs/custom'
    | '/portal/jobs/detail'
    | '/portal/jobs/inter'
    | '/portal/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/portal'
    | '/portal/monitor'
    | '/portal/overview'
    | '/portal/templates'
    | '/admin/'
    | '/auth/'
    | '/portal/'
    | '/portal/jobs/detail'
    | '/portal/jobs/new'
    | '/admin/accounts/$id'
    | '/admin/data/$id'
    | '/admin/files/$'
    | '/admin/jobs/$name'
    | '/admin/monitor/gpu'
    | '/admin/monitor/idle'
    | '/admin/monitor/network'
    | '/admin/users/$name'
    | '/ingress/jupyter/$name'
    | '/portal/files/$'
    | '/portal/monitor/gpu'
    | '/portal/monitor/idle'
    | '/portal/monitor/network'
    | '/portal/overview/$node'
    | '/portal/settings/user'
    | '/portal/users/$name'
    | '/admin/accounts/'
    | '/admin/cronjobs/'
    | '/admin/data/'
    | '/admin/jobs/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/portal/overview/'
    | '/portal/templates/'
    | '/admin/cluster/nodes/$node'
    | '/admin/env/registry/$name'
    | '/portal/data/blocks/$id'
    | '/portal/data/datasets/$id'
    | '/portal/data/models/$id'
    | '/portal/env/registry/$name'
    | '/portal/jobs/detail/$name'
    | '/portal/jobs/new/emias-job'
    | '/portal/jobs/new/emias-jupyter-job'
    | '/portal/jobs/new/jupyter-job'
    | '/portal/jobs/new/pytorch-ddp-job'
    | '/portal/jobs/new/seacs-job'
    | '/portal/jobs/new/single-job'
    | '/portal/jobs/new/tensorflow-ps-job'
    | '/admin/cluster/nodes/'
    | '/admin/cluster/resources/'
    | '/admin/env/images/'
    | '/admin/env/registry/'
    | '/portal/data/blocks/'
    | '/portal/data/datasets/'
    | '/portal/data/models/'
    | '/portal/env/images/'
    | '/portal/env/registry/'
    | '/portal/jobs/custom/'
    | '/portal/jobs/detail/'
    | '/portal/jobs/inter/'
    | '/portal/jobs/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  IngressJupyterNameRoute: typeof IngressJupyterNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/templates': {
      id: '/portal/templates'
      path: '/templates'
      fullPath: '/portal/templates'
      preLoaderRoute: typeof PortalTemplatesRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/overview': {
      id: '/portal/overview'
      path: '/overview'
      fullPath: '/portal/overview'
      preLoaderRoute: typeof PortalOverviewRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/monitor': {
      id: '/portal/monitor'
      path: '/monitor'
      fullPath: '/portal/monitor'
      preLoaderRoute: typeof PortalMonitorRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/templates/': {
      id: '/portal/templates/'
      path: '/'
      fullPath: '/portal/templates/'
      preLoaderRoute: typeof PortalTemplatesIndexRouteImport
      parentRoute: typeof PortalTemplatesRouteRoute
    }
    '/portal/overview/': {
      id: '/portal/overview/'
      path: '/'
      fullPath: '/portal/overview/'
      preLoaderRoute: typeof PortalOverviewIndexRouteImport
      parentRoute: typeof PortalOverviewRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data/': {
      id: '/admin/data/'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cronjobs/': {
      id: '/admin/cronjobs/'
      path: '/cronjobs'
      fullPath: '/admin/cronjobs'
      preLoaderRoute: typeof AdminCronjobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/users/$name': {
      id: '/portal/users/$name'
      path: '/users/$name'
      fullPath: '/portal/users/$name'
      preLoaderRoute: typeof PortalUsersNameRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/settings/user': {
      id: '/portal/settings/user'
      path: '/settings/user'
      fullPath: '/portal/settings/user'
      preLoaderRoute: typeof PortalSettingsUserRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/overview/$node': {
      id: '/portal/overview/$node'
      path: '/$node'
      fullPath: '/portal/overview/$node'
      preLoaderRoute: typeof PortalOverviewNodeRouteImport
      parentRoute: typeof PortalOverviewRouteRoute
    }
    '/portal/monitor/network': {
      id: '/portal/monitor/network'
      path: '/network'
      fullPath: '/portal/monitor/network'
      preLoaderRoute: typeof PortalMonitorNetworkRouteImport
      parentRoute: typeof PortalMonitorRouteRoute
    }
    '/portal/monitor/idle': {
      id: '/portal/monitor/idle'
      path: '/idle'
      fullPath: '/portal/monitor/idle'
      preLoaderRoute: typeof PortalMonitorIdleRouteImport
      parentRoute: typeof PortalMonitorRouteRoute
    }
    '/portal/monitor/gpu': {
      id: '/portal/monitor/gpu'
      path: '/gpu'
      fullPath: '/portal/monitor/gpu'
      preLoaderRoute: typeof PortalMonitorGpuRouteImport
      parentRoute: typeof PortalMonitorRouteRoute
    }
    '/portal/files/$': {
      id: '/portal/files/$'
      path: '/files/$'
      fullPath: '/portal/files/$'
      preLoaderRoute: typeof PortalFilesSplatRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/ingress/jupyter/$name': {
      id: '/ingress/jupyter/$name'
      path: '/ingress/jupyter/$name'
      fullPath: '/ingress/jupyter/$name'
      preLoaderRoute: typeof IngressJupyterNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$name': {
      id: '/admin/users/$name'
      path: '/users/$name'
      fullPath: '/admin/users/$name'
      preLoaderRoute: typeof AdminUsersNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/monitor/network': {
      id: '/admin/monitor/network'
      path: '/monitor/network'
      fullPath: '/admin/monitor/network'
      preLoaderRoute: typeof AdminMonitorNetworkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/monitor/idle': {
      id: '/admin/monitor/idle'
      path: '/monitor/idle'
      fullPath: '/admin/monitor/idle'
      preLoaderRoute: typeof AdminMonitorIdleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/monitor/gpu': {
      id: '/admin/monitor/gpu'
      path: '/monitor/gpu'
      fullPath: '/admin/monitor/gpu'
      preLoaderRoute: typeof AdminMonitorGpuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/$name': {
      id: '/admin/jobs/$name'
      path: '/jobs/$name'
      fullPath: '/admin/jobs/$name'
      preLoaderRoute: typeof AdminJobsNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/files/$': {
      id: '/admin/files/$'
      path: '/files/$'
      fullPath: '/admin/files/$'
      preLoaderRoute: typeof AdminFilesSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data/$id': {
      id: '/admin/data/$id'
      path: '/data/$id'
      fullPath: '/admin/data/$id'
      preLoaderRoute: typeof AdminDataIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts/$id': {
      id: '/admin/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/admin/accounts/$id'
      preLoaderRoute: typeof AdminAccountsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/jobs/new': {
      id: '/portal/jobs/new'
      path: '/jobs/new'
      fullPath: '/portal/jobs/new'
      preLoaderRoute: typeof PortalJobsNewRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/detail': {
      id: '/portal/jobs/detail'
      path: '/jobs/detail'
      fullPath: '/portal/jobs/detail'
      preLoaderRoute: typeof PortalJobsDetailRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/new/': {
      id: '/portal/jobs/new/'
      path: '/'
      fullPath: '/portal/jobs/new/'
      preLoaderRoute: typeof PortalJobsNewIndexRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/inter/': {
      id: '/portal/jobs/inter/'
      path: '/jobs/inter'
      fullPath: '/portal/jobs/inter'
      preLoaderRoute: typeof PortalJobsInterIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/detail/': {
      id: '/portal/jobs/detail/'
      path: '/'
      fullPath: '/portal/jobs/detail/'
      preLoaderRoute: typeof PortalJobsDetailIndexRouteImport
      parentRoute: typeof PortalJobsDetailRouteRoute
    }
    '/portal/jobs/custom/': {
      id: '/portal/jobs/custom/'
      path: '/jobs/custom'
      fullPath: '/portal/jobs/custom'
      preLoaderRoute: typeof PortalJobsCustomIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/env/registry/': {
      id: '/portal/env/registry/'
      path: '/env/registry'
      fullPath: '/portal/env/registry'
      preLoaderRoute: typeof PortalEnvRegistryIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/env/images/': {
      id: '/portal/env/images/'
      path: '/env/images'
      fullPath: '/portal/env/images'
      preLoaderRoute: typeof PortalEnvImagesIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/data/models/': {
      id: '/portal/data/models/'
      path: '/data/models'
      fullPath: '/portal/data/models'
      preLoaderRoute: typeof PortalDataModelsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/data/datasets/': {
      id: '/portal/data/datasets/'
      path: '/data/datasets'
      fullPath: '/portal/data/datasets'
      preLoaderRoute: typeof PortalDataDatasetsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/data/blocks/': {
      id: '/portal/data/blocks/'
      path: '/data/blocks'
      fullPath: '/portal/data/blocks'
      preLoaderRoute: typeof PortalDataBlocksIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/env/registry/': {
      id: '/admin/env/registry/'
      path: '/env/registry'
      fullPath: '/admin/env/registry'
      preLoaderRoute: typeof AdminEnvRegistryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/env/images/': {
      id: '/admin/env/images/'
      path: '/env/images'
      fullPath: '/admin/env/images'
      preLoaderRoute: typeof AdminEnvImagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cluster/resources/': {
      id: '/admin/cluster/resources/'
      path: '/cluster/resources'
      fullPath: '/admin/cluster/resources'
      preLoaderRoute: typeof AdminClusterResourcesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cluster/nodes/': {
      id: '/admin/cluster/nodes/'
      path: '/cluster/nodes'
      fullPath: '/admin/cluster/nodes'
      preLoaderRoute: typeof AdminClusterNodesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/jobs/new/tensorflow-ps-job': {
      id: '/portal/jobs/new/tensorflow-ps-job'
      path: '/tensorflow-ps-job'
      fullPath: '/portal/jobs/new/tensorflow-ps-job'
      preLoaderRoute: typeof PortalJobsNewTensorflowPsJobRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/new/single-job': {
      id: '/portal/jobs/new/single-job'
      path: '/single-job'
      fullPath: '/portal/jobs/new/single-job'
      preLoaderRoute: typeof PortalJobsNewSingleJobRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/new/seacs-job': {
      id: '/portal/jobs/new/seacs-job'
      path: '/seacs-job'
      fullPath: '/portal/jobs/new/seacs-job'
      preLoaderRoute: typeof PortalJobsNewSeacsJobRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/new/pytorch-ddp-job': {
      id: '/portal/jobs/new/pytorch-ddp-job'
      path: '/pytorch-ddp-job'
      fullPath: '/portal/jobs/new/pytorch-ddp-job'
      preLoaderRoute: typeof PortalJobsNewPytorchDdpJobRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/new/jupyter-job': {
      id: '/portal/jobs/new/jupyter-job'
      path: '/jupyter-job'
      fullPath: '/portal/jobs/new/jupyter-job'
      preLoaderRoute: typeof PortalJobsNewJupyterJobRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/new/emias-jupyter-job': {
      id: '/portal/jobs/new/emias-jupyter-job'
      path: '/emias-jupyter-job'
      fullPath: '/portal/jobs/new/emias-jupyter-job'
      preLoaderRoute: typeof PortalJobsNewEmiasJupyterJobRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/new/emias-job': {
      id: '/portal/jobs/new/emias-job'
      path: '/emias-job'
      fullPath: '/portal/jobs/new/emias-job'
      preLoaderRoute: typeof PortalJobsNewEmiasJobRouteImport
      parentRoute: typeof PortalJobsNewRouteRoute
    }
    '/portal/jobs/detail/$name': {
      id: '/portal/jobs/detail/$name'
      path: '/$name'
      fullPath: '/portal/jobs/detail/$name'
      preLoaderRoute: typeof PortalJobsDetailNameRouteImport
      parentRoute: typeof PortalJobsDetailRouteRoute
    }
    '/portal/env/registry/$name': {
      id: '/portal/env/registry/$name'
      path: '/env/registry/$name'
      fullPath: '/portal/env/registry/$name'
      preLoaderRoute: typeof PortalEnvRegistryNameRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/data/models/$id': {
      id: '/portal/data/models/$id'
      path: '/data/models/$id'
      fullPath: '/portal/data/models/$id'
      preLoaderRoute: typeof PortalDataModelsIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/data/datasets/$id': {
      id: '/portal/data/datasets/$id'
      path: '/data/datasets/$id'
      fullPath: '/portal/data/datasets/$id'
      preLoaderRoute: typeof PortalDataDatasetsIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/data/blocks/$id': {
      id: '/portal/data/blocks/$id'
      path: '/data/blocks/$id'
      fullPath: '/portal/data/blocks/$id'
      preLoaderRoute: typeof PortalDataBlocksIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/env/registry/$name': {
      id: '/admin/env/registry/$name'
      path: '/env/registry/$name'
      fullPath: '/admin/env/registry/$name'
      preLoaderRoute: typeof AdminEnvRegistryNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cluster/nodes/$node': {
      id: '/admin/cluster/nodes/$node'
      path: '/cluster/nodes/$node'
      fullPath: '/admin/cluster/nodes/$node'
      preLoaderRoute: typeof AdminClusterNodesNodeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountsIdRoute: typeof AdminAccountsIdRoute
  AdminDataIdRoute: typeof AdminDataIdRoute
  AdminFilesSplatRoute: typeof AdminFilesSplatRoute
  AdminJobsNameRoute: typeof AdminJobsNameRoute
  AdminMonitorGpuRoute: typeof AdminMonitorGpuRoute
  AdminMonitorIdleRoute: typeof AdminMonitorIdleRoute
  AdminMonitorNetworkRoute: typeof AdminMonitorNetworkRoute
  AdminUsersNameRoute: typeof AdminUsersNameRoute
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
  AdminCronjobsIndexRoute: typeof AdminCronjobsIndexRoute
  AdminDataIndexRoute: typeof AdminDataIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminClusterNodesNodeRoute: typeof AdminClusterNodesNodeRoute
  AdminEnvRegistryNameRoute: typeof AdminEnvRegistryNameRoute
  AdminClusterNodesIndexRoute: typeof AdminClusterNodesIndexRoute
  AdminClusterResourcesIndexRoute: typeof AdminClusterResourcesIndexRoute
  AdminEnvImagesIndexRoute: typeof AdminEnvImagesIndexRoute
  AdminEnvRegistryIndexRoute: typeof AdminEnvRegistryIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountsIdRoute: AdminAccountsIdRoute,
  AdminDataIdRoute: AdminDataIdRoute,
  AdminFilesSplatRoute: AdminFilesSplatRoute,
  AdminJobsNameRoute: AdminJobsNameRoute,
  AdminMonitorGpuRoute: AdminMonitorGpuRoute,
  AdminMonitorIdleRoute: AdminMonitorIdleRoute,
  AdminMonitorNetworkRoute: AdminMonitorNetworkRoute,
  AdminUsersNameRoute: AdminUsersNameRoute,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
  AdminCronjobsIndexRoute: AdminCronjobsIndexRoute,
  AdminDataIndexRoute: AdminDataIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminClusterNodesNodeRoute: AdminClusterNodesNodeRoute,
  AdminEnvRegistryNameRoute: AdminEnvRegistryNameRoute,
  AdminClusterNodesIndexRoute: AdminClusterNodesIndexRoute,
  AdminClusterResourcesIndexRoute: AdminClusterResourcesIndexRoute,
  AdminEnvImagesIndexRoute: AdminEnvImagesIndexRoute,
  AdminEnvRegistryIndexRoute: AdminEnvRegistryIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalMonitorRouteRouteChildren {
  PortalMonitorGpuRoute: typeof PortalMonitorGpuRoute
  PortalMonitorIdleRoute: typeof PortalMonitorIdleRoute
  PortalMonitorNetworkRoute: typeof PortalMonitorNetworkRoute
}

const PortalMonitorRouteRouteChildren: PortalMonitorRouteRouteChildren = {
  PortalMonitorGpuRoute: PortalMonitorGpuRoute,
  PortalMonitorIdleRoute: PortalMonitorIdleRoute,
  PortalMonitorNetworkRoute: PortalMonitorNetworkRoute,
}

const PortalMonitorRouteRouteWithChildren =
  PortalMonitorRouteRoute._addFileChildren(PortalMonitorRouteRouteChildren)

interface PortalOverviewRouteRouteChildren {
  PortalOverviewNodeRoute: typeof PortalOverviewNodeRoute
  PortalOverviewIndexRoute: typeof PortalOverviewIndexRoute
}

const PortalOverviewRouteRouteChildren: PortalOverviewRouteRouteChildren = {
  PortalOverviewNodeRoute: PortalOverviewNodeRoute,
  PortalOverviewIndexRoute: PortalOverviewIndexRoute,
}

const PortalOverviewRouteRouteWithChildren =
  PortalOverviewRouteRoute._addFileChildren(PortalOverviewRouteRouteChildren)

interface PortalTemplatesRouteRouteChildren {
  PortalTemplatesIndexRoute: typeof PortalTemplatesIndexRoute
}

const PortalTemplatesRouteRouteChildren: PortalTemplatesRouteRouteChildren = {
  PortalTemplatesIndexRoute: PortalTemplatesIndexRoute,
}

const PortalTemplatesRouteRouteWithChildren =
  PortalTemplatesRouteRoute._addFileChildren(PortalTemplatesRouteRouteChildren)

interface PortalJobsDetailRouteRouteChildren {
  PortalJobsDetailNameRoute: typeof PortalJobsDetailNameRoute
  PortalJobsDetailIndexRoute: typeof PortalJobsDetailIndexRoute
}

const PortalJobsDetailRouteRouteChildren: PortalJobsDetailRouteRouteChildren = {
  PortalJobsDetailNameRoute: PortalJobsDetailNameRoute,
  PortalJobsDetailIndexRoute: PortalJobsDetailIndexRoute,
}

const PortalJobsDetailRouteRouteWithChildren =
  PortalJobsDetailRouteRoute._addFileChildren(
    PortalJobsDetailRouteRouteChildren,
  )

interface PortalJobsNewRouteRouteChildren {
  PortalJobsNewEmiasJobRoute: typeof PortalJobsNewEmiasJobRoute
  PortalJobsNewEmiasJupyterJobRoute: typeof PortalJobsNewEmiasJupyterJobRoute
  PortalJobsNewJupyterJobRoute: typeof PortalJobsNewJupyterJobRoute
  PortalJobsNewPytorchDdpJobRoute: typeof PortalJobsNewPytorchDdpJobRoute
  PortalJobsNewSeacsJobRoute: typeof PortalJobsNewSeacsJobRoute
  PortalJobsNewSingleJobRoute: typeof PortalJobsNewSingleJobRoute
  PortalJobsNewTensorflowPsJobRoute: typeof PortalJobsNewTensorflowPsJobRoute
  PortalJobsNewIndexRoute: typeof PortalJobsNewIndexRoute
}

const PortalJobsNewRouteRouteChildren: PortalJobsNewRouteRouteChildren = {
  PortalJobsNewEmiasJobRoute: PortalJobsNewEmiasJobRoute,
  PortalJobsNewEmiasJupyterJobRoute: PortalJobsNewEmiasJupyterJobRoute,
  PortalJobsNewJupyterJobRoute: PortalJobsNewJupyterJobRoute,
  PortalJobsNewPytorchDdpJobRoute: PortalJobsNewPytorchDdpJobRoute,
  PortalJobsNewSeacsJobRoute: PortalJobsNewSeacsJobRoute,
  PortalJobsNewSingleJobRoute: PortalJobsNewSingleJobRoute,
  PortalJobsNewTensorflowPsJobRoute: PortalJobsNewTensorflowPsJobRoute,
  PortalJobsNewIndexRoute: PortalJobsNewIndexRoute,
}

const PortalJobsNewRouteRouteWithChildren =
  PortalJobsNewRouteRoute._addFileChildren(PortalJobsNewRouteRouteChildren)

interface PortalRouteRouteChildren {
  PortalMonitorRouteRoute: typeof PortalMonitorRouteRouteWithChildren
  PortalOverviewRouteRoute: typeof PortalOverviewRouteRouteWithChildren
  PortalTemplatesRouteRoute: typeof PortalTemplatesRouteRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
  PortalJobsDetailRouteRoute: typeof PortalJobsDetailRouteRouteWithChildren
  PortalJobsNewRouteRoute: typeof PortalJobsNewRouteRouteWithChildren
  PortalFilesSplatRoute: typeof PortalFilesSplatRoute
  PortalSettingsUserRoute: typeof PortalSettingsUserRoute
  PortalUsersNameRoute: typeof PortalUsersNameRoute
  PortalDataBlocksIdRoute: typeof PortalDataBlocksIdRoute
  PortalDataDatasetsIdRoute: typeof PortalDataDatasetsIdRoute
  PortalDataModelsIdRoute: typeof PortalDataModelsIdRoute
  PortalEnvRegistryNameRoute: typeof PortalEnvRegistryNameRoute
  PortalDataBlocksIndexRoute: typeof PortalDataBlocksIndexRoute
  PortalDataDatasetsIndexRoute: typeof PortalDataDatasetsIndexRoute
  PortalDataModelsIndexRoute: typeof PortalDataModelsIndexRoute
  PortalEnvImagesIndexRoute: typeof PortalEnvImagesIndexRoute
  PortalEnvRegistryIndexRoute: typeof PortalEnvRegistryIndexRoute
  PortalJobsCustomIndexRoute: typeof PortalJobsCustomIndexRoute
  PortalJobsInterIndexRoute: typeof PortalJobsInterIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalMonitorRouteRoute: PortalMonitorRouteRouteWithChildren,
  PortalOverviewRouteRoute: PortalOverviewRouteRouteWithChildren,
  PortalTemplatesRouteRoute: PortalTemplatesRouteRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
  PortalJobsDetailRouteRoute: PortalJobsDetailRouteRouteWithChildren,
  PortalJobsNewRouteRoute: PortalJobsNewRouteRouteWithChildren,
  PortalFilesSplatRoute: PortalFilesSplatRoute,
  PortalSettingsUserRoute: PortalSettingsUserRoute,
  PortalUsersNameRoute: PortalUsersNameRoute,
  PortalDataBlocksIdRoute: PortalDataBlocksIdRoute,
  PortalDataDatasetsIdRoute: PortalDataDatasetsIdRoute,
  PortalDataModelsIdRoute: PortalDataModelsIdRoute,
  PortalEnvRegistryNameRoute: PortalEnvRegistryNameRoute,
  PortalDataBlocksIndexRoute: PortalDataBlocksIndexRoute,
  PortalDataDatasetsIndexRoute: PortalDataDatasetsIndexRoute,
  PortalDataModelsIndexRoute: PortalDataModelsIndexRoute,
  PortalEnvImagesIndexRoute: PortalEnvImagesIndexRoute,
  PortalEnvRegistryIndexRoute: PortalEnvRegistryIndexRoute,
  PortalJobsCustomIndexRoute: PortalJobsCustomIndexRoute,
  PortalJobsInterIndexRoute: PortalJobsInterIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  IngressJupyterNameRoute: IngressJupyterNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
